### ISSUE TITLE
No way to specify port when using swarm.discovery.query attribute

### ISSUE THREAD

**Issue by skaczor** [tacchino/swarm#5]
For example, with consul, there are two ways to specify the discovery url:
1. Specify host as a string
2. Specify query

The first way allows to specify host:port as a string, but suffers from not being very portable. The second way is more portable, but can't specify port.

Currently, the only option I see is to wrap the recipe in my own and set the swarm.discovery.host attribute based on search results, with the port number appended at the end. Is there any other way? Shouldn't the port be its own attribute instead?

**Comment by tacchino** [comment]
@skaczor Take a look and see if that gives you the control you need

**Comment by skaczor** [comment]
That worked perfectly! Thanks.
