### ISSUE TITLE
Docker Swarm 17.x 

### ISSUE THREAD

**Issue by mshahat** [tacchino/swarm#8]
Hi, 

Do you see this cookbook still usable with newer Docker versions ? 

I'm using Docker cookbook to install and run the Docker engine on my nodes, and willing to use this cookbook to create a Swarm of x Managers and y Workers

Thanks,

**Comment by tacchino** [comment]
Hey, @mshahat I would be surprised if it did, I haven't personally been using this for quite some time. You are welcome to try / fork / PR whatever.
